proxy:
  restart: always
  image: jwilder/nginx-proxy
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro
  - /usr/share/nginx/html
  - /etc/nginx/vhost.d
  - /mnt/jade-notebooks/certs:/etc/nginx/certs:ro
  - ./htpasswd:/etc/nginx/htpasswd
  environment:
    - DEFAULT_HOST=devel.jupyter.informaticslab.co.uk
  ports:
  - 80:80
  - 443:443

letsencrypt:
  restart: always
  image: thomastweets/docker-letsencrypt-nginx-proxy-companion
  volumes:
   - /mnt/jade-notebooks/certs:/etc/nginx/certs:rw
   - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
   - proxy

jupyter:
  restart: always
  build: ./jupyterhub
  command: [jupyterhub, --no-ssl]
  env_file: /usr/local/share/jade/jade-secrets
  volumes:
    - /usr/local/share/jade/docker/master/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    - /mnt/jade-notebooks/home:/mnt/jade-notebooks/home
    - /mnt/jade-notebooks/database:/mnt/jade-notebooks/database
  environment:
    - VIRTUAL_HOST=devel.jupyter.informaticslab.co.uk
    - VIRTUAL_PORT=8000
    - LETSENCRYPT_HOST=devel.jupyter.informaticslab.co.uk
    - LETSENCRYPT_EMAIL=jacob.tomlinson@informaticslab.co.uk
    - DOCKER_HOST=swarm-master:4000
  links:
    - swarm-master
  ports:
    - 8081:8081

swarm-master:
  restart: always
  image: swarm
  ports:
    - 4000:4000
  command: "manage -H :4000 --replication --advertise localhost:4000 consul://consul:8500"
  links:
    - consul

consul:
  restart: always
  image: progrium/consul
  ports:
    - 8500:8500
  command: "-server -bootstrap"
